services:
  backend:
    container_name: aatmunn-api
    image: aatmunn-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - ollama
    volumes:
      - ./api:/code/api
      - ./static:/code/static
    expose:
      - "8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - aatmunn

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./static/ollama:/root/.ollama
      - ./static/scripts/entrypoint.sh:/entrypoint.sh
    tty: true
    restart: unless-stopped
    attach: false
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - aatmunn

  frontend:
    container_name: aatmunn-frontend
    image: aatmunn-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    # volumes:
    #   - ./frontend:/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - aatmunn

networks:
  aatmunn:
    name: aatmunn
    external: false