from typing_extensions import List, TypedDict
from langchain_core.documents import Document
from api import rag, llm, schema
from langgraph.graph import START, StateGraph
import json


class State(TypedDict):
    """
    Represents the state of the graph.

    Attributes:
        query (str): The query being asked.
        context (List[Document]): A list of documents retrieved from the vector store.
        navigation (schema.Navigation): The navigation information generated by the model.
    """

    query: str
    context: List[Document]
    navigation: schema.Navigation


def retrieve(state: State):
    """
    Retrieves documents from the vector store based on the query in the state.

    Args:
        state (State): The current state of the graph.

    Returns:
        dict: A dictionary containing the retrieved documents in the 'context' key.
    """
    vectorstore = rag.get_vectorstore()
    retriever = vectorstore.as_retriever(search_kwargs={"k": 3})
    retrieved_docs = retriever.invoke(input=state["query"])
    print(f"{retrieved_docs=}")
    return {"context": retrieved_docs}


def generate(state: State):
    """
    Generates a navigation response based on the retrieved context and the query.

    Args:
        state (State): The current state of the graph.

    Returns:
        dict: A dictionary containing the generated navigation information in the 'navigation' key.
    """
    context = {}
    id_mapping = {}
    for i, doc in enumerate(state["context"], start=1):
        id_mapping[i] = doc.id
        context[i] = {
            "id": i,
            "description": doc.page_content,
        }

    print("CONTEXT \n\n\n\n\n\n", context ,"\n\n\n\n\n")
    try:
        response = llm.rag_chain.invoke(
            {"query": state["query"], "context": json.dumps(context)}
        )
        if response:
            id = response.id
            response.id = id_mapping.get(id, None)
            return {"navigation": response}
    except Exception as e:
        print(f"Failed to get Navigation due to: {e}")


graph_builder = StateGraph(State).add_sequence([retrieve, generate])
graph_builder.add_edge(START, "retrieve")
navigation_graph = graph_builder.compile()
